version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: kreditinfo_app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    networks:
      - kreditinfo_network
    depends_on:
      - db
      - minio
